# Generated by Django 4.0 on 2021-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(max_length=250)),
                ('short_url', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'url_shortener',
                'ordering': ['-created_at'],
            },
        ),
    ]
