# Generated by Django 4.0 on 2021-12-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_short_options_alter_short_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='short',
            table='url_shortener',
        ),
    ]
