# Generated by Django 4.0 on 2021-12-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_alter_short_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
